site_name: Yanyh's Summary
site_dir: ../docs/

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    # - navigation.tabs
    - navigation.sections
    # - navigation.expand
    # - navigation.top
    # - navigation.tabs.sticky

nav:
    - Overview: index.md

    - Java: 
        - 'test.md'

    - 数据库:
        # - 'Writing your docs': 'test.md'
        - 'test.md'

    - 运维:
        - 'test.md'
        # - 'Release Notes': 'release-notes.md'

    - 计算机基础:
        - 'test.md'

    - 大数据/云原生:
        - 'test.md'

    - 设计模式:
        - 'test.md'


repo_url: https://github.com/jackyar/jackyar.github.io
repo_name: GitHub Address
